In [9]:
import cv2
import numpy as np

In [ ]:
simple_image = np.zeros(shape=(1024,1024,3))

simple_image[300:500, 300] = 255
simple_image[300:500, 500] = 255
simple_image[300, 300:500] = 255
simple_image[500, 300:500] = 255

cv2.imwrite('part2-images/simple_img1.jpg', simple_image)

In [13]:
simple_image = np.zeros(shape=(1024,1024,3))

simple_image[700:900, 700] = 255
simple_image[700:900, 900] = 255
simple_image[700, 700:900] = 255
simple_image[900, 700:900] = 255

cv2.imwrite('part2-images/simple_img2.jpg', simple_image)

True

In [17]:
first_corners = np.array([
    [300, 300, 500, 500],
    [300, 500, 300, 500],
    [1, 1, 1]
])

second_corners = np.array([
    [700, 700, 900, 900],
    [700, 900, 700, 900],
    [1, 1, 1]
])

In [99]:
first_corners = np.array([
    [300, 0, 1],
    [0, 300, 1],
])

second_corners = np.array([700, 700])

In [100]:
ans = np.linalg.lstsq(first_corners, second_corners)

C:\Ed\Anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [101]:
ans[0]

array([2.33328148, 2.33328148, 0.01555521])

In [102]:
np.matmul(first_corners[0], ans[0])

699.9999999999999

In [89]:
first_corners[1]

array([  0, 500,   1])

In [90]:
ans[0]

array([2.33329541, 1.79997724, 0.01137761])