In [1]:
import cv2
import numpy as np

In [22]:
translation_matches = [
    [(300, 300), (400, 500)]
]

translation_matches_test = [
    [(401, 300), (501, 500)]
]

euclidean_matches = [
    [(487, 300), (555, 25)], 
    [(500, 319), (575, 35)]
]

euclidean_matches_test = [
    [(434, 300), (510, 50)]
]

affine_matches = [
    [(300, 300), (400, 350)],
    [(401, 300), (501, 350)],
    [(300, 302), (398, 351)]
]

affine_matches_test = [
    [(500, 302), (598, 351)]
]

projection_matches = [
    [(318, 256), (141, 131)],
    [(534, 372), (480, 159)],
    [(316, 670), (493, 630)],
    [(73, 473), (64, 601)]
]

In [8]:
simple_img = cv2.imread('part2-images/Simple.jpg')

In [12]:
def Apply_Transformation_Two(img, transform_array):

    # Initialize new image
    new_img = np.zeros(shape=img.shape)

    # Loop through coordinates and
    # apply inverse transformation
    for r in range(img.shape[0]):
        for c in range(img.shape[1]):
            current_coor = np.array([[c, r, 1]])
            new_coor = np.matmul(current_coor, transform_array)
            new_x = new_coor[0] / new_coor[2]
            new_y = new_coor[1] / new_coor[2]
            # Update new image if old coordinate
            # is within the image coordinate bounds
            if new_y < img.shape[0] and \
                new_x < img.shape[1] and \
                new_y > 0 and \
                new_x > 0:

                    new_img[r, c] = img[int(new_y), int(new_x)]

    return new_img

In [23]:
translation_input = np.array([
    [translation_matches[0][0][0], 0],
    [0, translation_matches[0][0][1]]
])

print('Linear Equation Array:')
print(translation_input)
print()

translation_output = np.array([
    translation_matches[0][1][0], translation_matches[0][1][1]
])

print('Equation Output:')
print(translation_output)
print()

translation_solved = np.linalg.solve(translation_input, translation_output)

print('Equation Solved:')
print(translation_solved)
print()

translation_transform = np.array([
    [translation_solved[0], 0, 0],
    [0, translation_solved[1], 0],
    [0, 0, 1]
])

print('Transfrom Matrix:')
print(translation_transform)
print()

translation_original = np.array([
    translation_matches_test[0][0][0], translation_matches_test[0][0][1], 1
])

translation_new = np.matmul(translation_original, translation_transform)

print(f'Test: ({translation_new[0] / translation_new[2]}, {translation_new[1] / translation_new[2]}) = {translation_matches_test[0][1]}')

Linear Equation Array:
[[300   0]
 [  0 300]]

Equation Output:
[400 500]

Equation Solved:
[1.33333333 1.66666667]

Transfrom Matrix:
[[1.33333333 0.         0.        ]
 [0.         1.66666667 0.        ]
 [0.         0.         1.        ]]

Test: [534.66666667 500.           1.        ] = (501, 500)


In [20]:
euclidean_input = np.array([
    [euclidean_matches[0][0][0], euclidean_matches[0][0][1], 0, 0],
    [0, 0, euclidean_matches[0][0][0], euclidean_matches[0][0][1]],
    [euclidean_matches[1][0][0], euclidean_matches[1][0][1], 0, 0],
    [0, 0, euclidean_matches[1][0][0], euclidean_matches[1][0][1]],
])

print('Linear Equation Array:')
print(euclidean_input)
print()

euclidean_output = np.array([
    euclidean_matches[0][1][0], euclidean_matches[0][1][1], euclidean_matches[1][1][0], euclidean_matches[1][1][1]
])

print('Equation Output:')
print(euclidean_output)
print()

euclidean_solved = np.linalg.solve(euclidean_input, euclidean_output)

print('Equation Solved:')
print(euclidean_solved)
print()

euclidean_transform = np.array([
    [euclidean_solved[0], euclidean_solved[1], 0],
    [euclidean_solved[2], euclidean_solved[3], 0],
    [0, 0, 1]
])

print('Transfrom Matrix:')
print(euclidean_transform)
print()

euclidean_original = np.array([
    [euclidean_matches_test[0][0][0], euclidean_matches_test[0][0][1], 1],
])

euclidean_new = np.matmul(euclidean_original[0], euclidean_transform)

print(f'Test: ({euclidean_new[0] / euclidean_new[2]}, {euclidean_new[1] / euclidean_new[2]}) = {euclidean_matches_test[0][1]}')

Linear Equation Array:
[[487 300   0   0]
 [  0   0 487 300]
 [500 319   0   0]
 [  0   0 500 319]]

Equation Output:
[555  25 575  35]

Equation Solved:
[ 0.8490566   0.47169811 -0.47169811  0.8490566 ]

Transfrom Matrix:
[[ 0.8490566   0.47169811  0.        ]
 [-0.47169811  0.8490566   0.        ]
 [ 0.          0.          1.        ]]

Test 1: [271.98113208 484.43396226   1.        ] = (555, 25)
Test 1: [274.05660377 506.69811321   1.        ] = (575, 35)


In [24]:
affine_input = np.array([
    [affine_matches[0][0][0], affine_matches[0][0][1], 1, 0, 0, 0],
    [0, 0, 0, affine_matches[0][0][0], affine_matches[0][0][1], 1],
    [affine_matches[1][0][0], affine_matches[1][0][1], 1, 0, 0, 0],
    [0, 0, 0, affine_matches[1][0][0], affine_matches[1][0][1], 1],
    [affine_matches[2][0][0], affine_matches[2][0][1], 1, 0, 0, 0],
    [0, 0, 0, affine_matches[2][0][0], affine_matches[2][0][1], 1],
])

print('Linear Equation Array:')
print(affine_input)
print()

affine_output = np.array([
    affine_matches[0][1][0], affine_matches[0][1][1], affine_matches[1][1][0], affine_matches[1][1][1], affine_matches[2][1][0], affine_matches[2][1][1]
])

print('Equation Output:')
print(affine_output)
print()

affine_solved = np.linalg.solve(affine_input, affine_output)

print('Equation Solved:')
print(affine_solved)
print()

affine_transform = np.array([
    [affine_solved[0], affine_solved[1], 0],
    [affine_solved[2], affine_solved[3], 0],
    [0, 0, 1]
])

print('Transfrom Matrix:')
print(affine_transform)
print()

affine_original = np.array([
    [affine_matches_test[0][0][0], affine_matches_test[0][0][1], 1],
])

affine_new = np.matmul(affine_original[0], affine_transform)

print(f'Test: ({affine_new[0] / affine_new[2]}, {affine_new[1] / affine_new[2]}) = {affine_matches_test[0][1]}')

Linear Equation Array:
[[300 300   1   0   0   0]
 [  0   0   0 300 300   1]
 [401 300   1   0   0   0]
 [  0   0   0 401 300   1]
 [300 302   1   0   0   0]
 [  0   0   0 300 302   1]]

Equation Output:
[400 350 501 350 398 351]

Equation Solved:
[ 1.00000000e+00 -1.00000000e+00  4.00000000e+02  2.12631243e-16
  5.00000000e-01  2.00000000e+02]

Transfrom Matrix:
[[ 1.00000000e+00 -1.00000000e+00  0.00000000e+00]
 [ 4.00000000e+02  2.12631243e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]

Test: (121299.99999999962, -499.99999999999824) = (598, 351)
